# Generated by Django 4.1.6 on 2023-05-16 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveSearchAndSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.TextField(blank=True, null=True)),
                ('selected_products', models.ManyToManyField(to='products.product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_selection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
